kube-HPC/nodejs-wrapper.hkube

- .travis.yml
- lib/algorunner.js
- lib/utils/tracer.js
- package-lock.json
- package.json
- tests/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/4)
> add tracing to algo

- lib/algorunner.js
- lib/utils/tracer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/7)
> add tracing to data adapter

- lib/utils/tracer.js
- tests/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/10)
> fix jaeger tracing for non async methods

- lib/config.js
- lib/utils/formatters.js
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/11)
> add queue concurrency config

- package-lock.json
- package.json
- tests/setup.js
- tests/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/12)
> update data-adapter, add test

- lib/algorunner.js
- lib/config.js
- lib/consts/messages.js
- package-lock.json
- package.json
- tests/debugTests.js
- tests/setup.js
- tests/test.js
- tests/testRun.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)
> feat: apply all changes

- lib/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/16)
> fix STORAGE_MAX_CACHE_SIZE

- .eslintrc.js
- lib/algorunner.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/17)
> feat: save in cache only if has childs

- lib/algorunner.js
- lib/codeApi/codeApi.js
- lib/consts/messages.js
- tests/mocks/algorithmCode/index.js
- tests/mocks/algorithmCode/indexPipe.js
- tests/mocks/algorithmCode/indexRawPipe.js
- tests/mocks/algorithmCode/package.json
- tests/stubs/ws.js
- tests/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/19)
> add codeApi to node wrapper

- lib/codeApi/codeApi.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/22)
> subpipleline fill result

- lib/codeApi/codeApi.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/23)
> fix to support algorithm done

- index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/26)
> feat: logger format

- lib/StatelessWrapper.js
- lib/config.js
- package-lock.json
- package.json
- tests/streaming.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/27)
> feat: streaming

- lib/algorunner.js
- package-lock.json
- package.json
- tests/debugTests.js
- tests/setup.js
- tests/streaming.js
- tests/test.js
- tests/testRun.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/29)
> feat: more improvements

- lib/algorunner.js
- lib/codeApi/codeApi.js
- tests/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)
> start algorithm save input in code api

- lib/algorunner.js
- lib/websocket/ws.js
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/30)
> Streaming round 3

- lib/algorunner.js
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/31)
> Streaming round 4

- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/32)
> feat: streaming duration

- index.js
- lib/algorunner.js
- lib/codeApi/codeApi.js
- lib/consts/messages.js
- package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/36)
> datasource

- lib/algorunner.js
- lib/consts/messages.js
- lib/debug.js
- lib/utils/stdOutRedirect.js
- lib/websocket/ws.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)
> redirect logs for debug

- lib/websocket/ws.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/39)
> log message correction
